<?php
/**
 * Plugin Name:     Email Generator
 * Plugin URI:      PLUGIN SITE HERE
 * Description:     Generate your own HTML emails using a combination of templates and shortcodes. Then copy-and-paste the code generated by this plugin into your favorite email service.
 * Author:          TheWebist
 * Author URI:      YOUR SITE HERE
 * Text Domain:     email-generator
 * Domain Path:     /languages
 * Version:         0.1.0
 *
 * @package         Email_Generator
 */

// Your code starts here.
